name: semgrep

on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions: read-all

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          repository: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      - name: Install Semgrep CLI
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install semgrep
      - name: Run Semgrep
        run: semgrep scan --config auto --error
